import blog from "../../assets/images/blog.jpg";
export const blogData = [
  {
    id: 3,
    image: blog,
    title: "Snakebite Treatment Advances",
    title_ar: "تطورات علاج لدغات الثعابين",
    date: "June 2025",
    country: "USA",
    country_ar: "الولايات المتحدة الأمريكية",
    short_description: "New methods are improving snakebite recovery rates in rural areas.",
    short_description_ar: "أساليب جديدة تحسن معدلات التعافي من لدغات الثعابين في المناطق الريفية.",
    description: "Recent studies show that integrating AI with field diagnostics has significantly improved snakebite treatment protocols.",
    description_ar: "أظهرت الدراسات الحديثة أن دمج الذكاء الاصطناعي مع التشخيص الميداني قد حسّن بشكل كبير بروتوكولات علاج لدغات الثعابين."
  },
  {
    id: 4,
    image: blog,
    title: "Mapping Snake Habitats",
    title_ar: "رسم خرائط موائل الثعابين",
    date: "May 2025",
    country: "India",
    country_ar: "الهند",
    short_description: "Researchers are using satellite data to track snake populations.",
    short_description_ar: "يستخدم الباحثون بيانات الأقمار الصناعية لتتبع تجمعات الثعابين.",
    description: "Satellite imaging combined with local surveys is helping scientists understand snake migration and habitat changes.",
    description_ar: "يساعد التصوير بالأقمار الصناعية مع المسوحات المحلية العلماء على فهم هجرة الثعابين وتغير موائلها."
  },
  {
    id: 5,
    image: blog,
    title: "Venom Composition Insights",
    title_ar: "رؤى حول تركيب السموم",
    date: "April 2025",
    country: "Brazil",
    country_ar: "البرازيل",
    short_description: "Genetic sequencing reveals new venom compounds.",
    short_description_ar: "يكشف التسلسل الجيني عن مركبات سم جديدة.",
    description: "Advanced sequencing has identified previously unknown proteins in snake venom, opening doors for new treatments.",
    description_ar: "حدد التسلسل المتقدم بروتينات غير معروفة سابقًا في سم الثعابين، مما يفتح المجال لعلاجات جديدة."
  },
  {
    id: 6,
    image: blog,
    title: "AI in Snake Classification",
    title_ar: "الذكاء الاصطناعي في تصنيف الثعابين",
    date: "March 2025",
    country: "Egypt",
    country_ar: "مصر",
    short_description: "AI tools are helping classify snake species faster.",
    short_description_ar: "تساعد أدوات الذكاء الاصطناعي في تصنيف أنواع الثعابين بسرعة أكبر.",
    description: "Machine learning models trained on thousands of images are now able to classify snake species with high accuracy.",
    description_ar: "نماذج التعلم الآلي المدربة على آلاف الصور قادرة الآن على تصنيف أنواع الثعابين بدقة عالية."
  },
  {
    id: 7,
    image: blog,
    title: "Community Awareness Campaigns",
    title_ar: "حملات التوعية المجتمعية",
    date: "February 2025",
    country: "South Africa",
    country_ar: "جنوب أفريقيا",
    short_description: "Local campaigns are reducing snakebite incidents.",
    short_description_ar: "تقلل الحملات المحلية من حوادث لدغات الثعابين.",
    description: "Educational efforts in rural communities have led to a noticeable drop in snakebite cases.",
    description_ar: "أدت الجهود التعليمية في المجتمعات الريفية إلى انخفاض ملحوظ في حالات لدغات الثعابين."
  },
  {
    id: 8,
    image: blog,
    title: "Venom Data Visualization",
    title_ar: "تصوير بيانات السموم",
    date: "January 2025",
    country: "Australia",
    country_ar: "أستراليا",
    short_description: "Interactive dashboards show venom trends.",
    short_description_ar: "لوحات المعلومات التفاعلية تعرض اتجاهات السموم.",
    description: "New dashboards allow researchers to explore venom toxicity patterns across regions.",
    description_ar: "تتيح لوحات المعلومات الجديدة للباحثين استكشاف أنماط سمية السموم عبر المناطق."
  },
  {
    id: 9,
    image: blog,
    title: "Antivenom Supply Chains",
    title_ar: "سلاسل توريد مضادات السموم",
    date: "December 2024",
    country: "Mexico",
    country_ar: "المكسيك",
    short_description: "Efforts are underway to improve antivenom distribution.",
    short_description_ar: "تُبذل جهود لتحسين توزيع مضادات السموم.",
    description: "Logistics optimization is helping ensure timely delivery of antivenoms to remote areas.",
    description_ar: "يساعد تحسين الخدمات اللوجستية في ضمان توصيل مضادات السموم في الوقت المناسب إلى المناطق النائية."
  },
  {
    id: 10,
    image: blog,
    title: "Snake Ecology Studies",
    title_ar: "دراسات بيئة الثعابين",
    date: "November 2024",
    country: "Thailand",
    country_ar: "تايلاند",
    short_description: "Ecological studies reveal snake behavior patterns.",
    short_description_ar: "تكشف الدراسات البيئية عن أنماط سلوك الثعابين.",
    description: "Field research is uncovering how seasonal changes affect snake movement and interactions.",
    description_ar: "تكشف الأبحاث الميدانية كيف تؤثر التغيرات الموسمية على حركة الثعابين وتفاعلاتها."
  },
  {
    id: 11,
    image: blog,
    title: "Venom Research Collaboration",
    title_ar: "تعاون بحثي في مجال السموم",
    date: "October 2024",
    country: "Germany",
    country_ar: "ألمانيا",
    short_description: "International teams are sharing venom data.",
    short_description_ar: "تتبادل الفرق الدولية بيانات السموم.",
    description: "Collaborative platforms are enabling researchers to pool venom data for broader analysis.",
    description_ar: "تتيح المنصات التعاونية للباحثين تجميع بيانات السموم لتحليل أوسع."
  },
  {
    id: 12,
    image: blog,
    title: "Snakebite First Aid Training",
    title_ar: "تدريب الإسعافات الأولية للدغات الثعابين",
    date: "September 2024",
    country: "Indonesia",
    country_ar: "إندونيسيا",
    short_description: "Training programs are teaching snakebite response.",
    short_description_ar: "برامج التدريب تعلم كيفية التعامل مع لدغات الثعابين.",
    description: "Workshops are equipping locals with practical skills to respond to snakebites effectively.",
    description_ar: "تزود الورش السكان المحليين بمهارات عملية للتعامل مع لدغات الثعابين بفعالية."
  }
];
// src/components/Archive/data.js
export const archiveData = [
  { month: "January", year: 2025, count: 5 },
  { month: "February", year: 2025, count: 8 },
  { month: "March", year: 2025, count: 3 },
  { month: "April", year: 2025, count: 6 },
  { month: "May", year: 2025, count: 4 },
  { month: "June", year: 2025, count: 9 },
  { month: "July", year: 2025, count: 7 },
  { month: "August", year: 2025, count: 2 },
  { month: "September", year: 2025, count: 10 },
  { month: "October", year: 2025, count: 1 },
  { month: "November", year: 2025, count: 5 },
  { month: "December", year: 2025, count: 4 },

  { month: "January", year: 2024, count: 6 },
  { month: "February", year: 2024, count: 3 },
  { month: "March", year: 2024, count: 8 },
  { month: "April", year: 2024, count: 2 },
  { month: "May", year: 2024, count: 7 },
  { month: "June", year: 2024, count: 5 },
];
