import blog from "../../assets/images/blog.jpg";
export const Dblogs = [
  {
    id: 1,
    imgae: { blog },
    title: "Quantum Computing Basics",
    date: "January 2025",
    country: "USA",
    short_description: "An introduction to the world of quantum bits.",
    description:
      "Discover how qubits work and what makes quantum computers so powerful.",
  },
  {
    id: 2,
    imgae: { blog },
    title: "Urban Farming Trends",
    date: "February 2025",
    country: "CANADA",
    short_description: "How cities grow food in tiny spaces.",
    description:
      "Explore vertical gardens, rooftop farms, and community plots in modern cities.",
  },
  {
    id: 3,
    imgae: { blog },
    title: "AI in Healthcare",
    date: "March 2025",
    country: "UK",
    short_description: "Machine learning meets patient care.",
    description:
      "Learn how algorithms help diagnose diseases faster and more accurately.",
  },
  {
    id: 4,
    imgae: { blog },
    title: "Sustainable Architecture",
    date: "April 2025",
    country: "GERMANY",
    short_description: "Building green for the future.",
    description:
      "Discover materials and designs that reduce environmental impact.",
  },
  {
    id: 5,
    imgae: { blog },
    title: "Blockchain Beyond Crypto",
    date: "May 2025",
    country: "SWITZERLAND",
    short_description: "Distributed ledgers in real-world use.",
    description:
      "From supply chains to voting systems, see blockchain’s wider applications.",
  },
  {
    id: 6,
    imgae: { blog },
    title: "The Art of Minimalism",
    date: "June 2025",
    country: "JAPAN",
    short_description: "Living better with less.",
    description:
      "Understand the philosophy of simplicity in design and lifestyle.",
  },
  {
    id: 7,
    imgae: { blog },
    title: "VR in Education",
    date: "July 2025",
    country: "AUSTRALIA",
    short_description: "Immersive learning experiences.",
    description:
      "How virtual reality transforms classrooms into interactive worlds.",
  },
  {
    id: 8,
    imgae: { blog },
    title: "Renewable Energy 101",
    date: "August 2025",
    country: "BRAZIL",
    short_description: "Wind, solar, and beyond.",
    description: "A primer on the technologies powering a sustainable grid.",
  },
  {
    id: 9,
    imgae: { blog },
    title: "Cybersecurity Best Practices",
    date: "September 2025",
    country: "INDIA",
    short_description: "Protecting your digital life.",
    description: "Simple steps everyone can take to stay safe online.",
  },
  {
    id: 10,
    imgae: { blog },
    title: "Astrophotography Tips",
    date: "October 2025",
    country: "NEW ZEALAND",
    short_description: "Capturing the night sky.",
    description: "Gear, settings, and techniques for stunning star photos.",
  },
  {
    id: 11,
    imgae: { blog },
    title: "Biomimicry in Design",
    date: "November 2025",
    country: "SWEDEN",
    short_description: "Nature-inspired innovation.",
    description: "How designers mimic natural solutions for human problems.",
  },
  {
    id: 12,
    imgae: { blog },
    title: "Language Learning Hacks",
    date: "December 2025",
    country: "SPAIN",
    short_description: "Master a new tongue faster.",
    description: "Proven techniques and apps to boost your fluency.",
  },
  {
    id: 13,
    imgae: { blog },
    title: "Deep Sea Discoveries",
    date: "January 2024",
    country: "NORWAY",
    short_description: "Life beneath the waves.",
    description:
      "Recent finds from ocean-floor expeditions and their impact on science.",
  },
  {
    id: 14,
    imgae: { blog },
    title: "Ethical Fashion Movement",
    date: "February 2024",
    country: "FRANCE",
    short_description: "Clothes with a conscience.",
    description: "Brands and practices that prioritize workers and the planet.",
  },
  {
    id: 15,
    imgae: { blog },
    title: "Mars Habitat Designs",
    date: "March 2024",
    country: "USA",
    short_description: "Living on the Red Planet.",
    description: "Concepts for self-sustaining shelters on Mars.",
  },
  {
    id: 16,
    imgae: { blog },
    title: "Neuroplasticity Explained",
    date: "April 2024",
    country: "CANADA",
    short_description: "Rewiring the brain.",
    description: "How experiences shape neural pathways over a lifetime.",
  },
  {
    id: 17,
    imgae: { blog },
    title: "Gig Economy Insights",
    date: "May 2024",
    country: "MEXICO",
    short_description: "The rise of on-demand work.",
    description: "Challenges and opportunities for freelancers today.",
  },
  {
    id: 18,
    imgae: { blog },
    title: "Edge AI Innovations",
    date: "June 2024",
    country: "CHINA",
    short_description: "Processing at the edge.",
    description: "AI models running on-device for speed and privacy.",
  },
  {
    id: 19,
    imgae: { blog },
    title: "Smart Cities Overview",
    date: "July 2024",
    country: "SOUTH AFRICA",
    short_description: "Urban living reimagined.",
    description: "Connected infrastructure and data-driven city services.",
  },
  {
    id: 20,
    imgae: { blog },
    title: "AR Art Installations",
    date: "August 2024",
    country: "ITALY",
    short_description: "Augmented creativity.",
    description: "Artists blending digital layers with physical spaces.",
  },
];

// src/components/Archive/data.js
export const archiveData = [
  { month: "January", year: 2025, count: 5 },
  { month: "February", year: 2025, count: 8 },
  { month: "March", year: 2025, count: 3 },
  { month: "April", year: 2025, count: 6 },
  { month: "May", year: 2025, count: 4 },
  { month: "June", year: 2025, count: 9 },
  { month: "July", year: 2025, count: 7 },
  { month: "August", year: 2025, count: 2 },
  { month: "September", year: 2025, count: 10 },
  { month: "October", year: 2025, count: 1 },
  { month: "November", year: 2025, count: 5 },
  { month: "December", year: 2025, count: 4 },

  { month: "January", year: 2024, count: 6 },
  { month: "February", year: 2024, count: 3 },
  { month: "March", year: 2024, count: 8 },
  { month: "April", year: 2024, count: 2 },
  { month: "May", year: 2024, count: 7 },
  { month: "June", year: 2024, count: 5 },
];
